#ifndef TAPESISTER_TAPEHEAD_ACTIONS_H
#define TAPESISTER_TAPEHEAD_ACTIONS_H
enum { TS_TH_NONE, TS_TH_CANVAS, TS_TH_TILES, TS_TH_AUDIO, TS_TH_CAPTURE, TS_TH_CYCLE_CAPTURE, TS_TH_ROUTER, TS_TH_FX, TS_TH_PRISM, TS_TH_SISTER, TS_TH_FALLOUT, TS_TH_SAVE_DEFAULTS, TS_TH_SAVE_PROJECT, TS_TH_OPEN_PROJECT, TS_TH_PALETTE_IMPORT, TS_TH_PALETTE_EXPORT };
#endif
