#!/usr/bin/env python3
"""Bake deterministic cloud density/filaments; runtime only moves cached motes."""
import math
from pathlib import Path

def hash2(x, y, seed):
    n = (x * 374761393 + y * 668265263 + seed * 1442695041) & 0xffffffff
    n = ((n ^ (n >> 13)) * 1274126177) & 0xffffffff
    return (n ^ (n >> 16)) / 4294967295

def noise(x, y, seed):
    a, b = math.floor(x), math.floor(y)
    u, v = x-a, y-b
    u, v = u*u*(3-2*u), v*v*(3-2*v)
    return ((1-u)*hash2(a,b,seed)+u*hash2(a+1,b,seed))*(1-v) + ((1-u)*hash2(a,b+1,seed)+u*hash2(a+1,b+1,seed))*v

def fbm(x, y, seed):
    return sum(noise(x*2**i,y*2**i,seed+i)*w for i,w in enumerate((.55,.27,.12,.06)))

lines = ['/* Generated by scripts/generate-prism-nebula.py. No runtime field evaluation. */',
         'typedef struct { int8_t x,y; uint8_t density,spectrum,region; } TsPrismNebulaPoint;']
for side, seed in enumerate((21,37)):
    points=[]
    for y in range(-62,63):
        for x in range(-53,54):
            # Related asymmetric billows, hollow cavities, and curling ridges.
            u,v=x/44,y/52
            warp=fbm(u*2+5,v*2+8,seed)-.5
            envelope=math.exp(-1.3*((u+.23*math.sin(v*4+side))**2+(v*.82)**2))
            envelope*=max(0,1-(abs(x)/55)**8)*max(0,1-(abs(y)/65)**8)
            n=fbm(u*2.5+warp*1.7+8,v*2.5+warp+5,seed)
            ridge=math.exp(-((n-.52)/.048)**2)
            cavity=max(.03,min(1,(n-.28)*4))
            mass=envelope*cavity*(.23+.55*ridge+.4*n)
            # A luminous off-centre core, with branching matter around it.
            core=math.exp(-((u-(.26 if side else .4))**2/.075+(v+.06)**2/.11))
            mass=min(1,mass+.55*core)
            h=hash2(x,y,seed+99)
            if h>min(.97,mass*1.8+.035*envelope) or mass<.025:continue
            spectrum=fbm(u*1.6+3,v*1.6+7,seed+77)
            points.append((x,y,int(255*mass),int(255*spectrum),int(hash2(x//14,y//16,seed)*8)%8))
    lines.append(f'static const TsPrismNebulaPoint prism_nebula_{"output" if side else "source"}[] = {{')
    lines.extend('    {%d,%d,%d,%d,%d},'%p for p in points)
    lines.append('};')
    print(('source','output')[side],len(points),'motes')
Path(__file__).resolve().parents[1].joinpath('src/ts_prism_nebula_points.inc').write_text('\n'.join(lines)+'\n')
